name: Update Base Image Version

on:
  workflow_dispatch:

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      app_list: ${{ steps.set-matrix.outputs.app_list }}
    steps:
      - name: Calculate apps on the fly
        id: set-matrix
        run: |
          # Example: dynamically generate the app list (replace with your logic)
          apps='["test-argocd","ci-cd-diff-tools"]'
          echo "app_list=$apps" >> $GITHUB_OUTPUT

  echo-matrix:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{ fromJson(needs.prepare-matrix.outputs.app_list) }}
    steps:
      - name: Checkout ${{ matrix.app }} repository
        uses: actions/checkout@v4
        with:
          repository: shurikg/${{ matrix.app }}
          path: ${{ matrix.app }}
      - name: Echo app name
        run: echo "Checked out ${{ matrix.app }}"
