name: Update Base Image Version

on:
  workflow_dispatch:

jobs:
  echo-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - applications-specs
          - another-app
          - third-app
    steps:
      - name: Echo app name
        run: echo "Processing ${{ matrix.app }}"
